package ro.tuiasi.ac.agent;

import java.util.ArrayList;
import java.util.List;

/**
 * Represents the state of an optimization agent while processing a source code
 * file.
 *
 * <p>
 * This class stores the original source code, the final optimized code if one
 * is produced, the list of optimization steps executed by the agent, validation
 * errors from the latest failed attempt, and whether the optimization process
 * has been finalized.
 * </p>
 */
public class AgentState {

    /**
     * The original source code read from the analyzed file.
     */
    private String originalCode;

    /**
     * The final optimized source code generated by the agent.
     *
     * <p>
     * This value is usually set only when a generated proposal passes validation.
     * </p>
     */
    private String finalCode;

    /**
     * The list of optimization steps performed during the agent loop.
     */
    private List<AgentStep> steps;

    /**
     * Indicates whether the agent has successfully finalized the optimization
     * process.
     */
    private boolean isFinalized;

    /**
     * Validation errors from the most recent failed optimization attempt.
     */
    private String lastErrors;

    /**
     * Creates a new agent state using the provided original source code.
     *
     * <p>
     * The steps list is initialized as empty and the state is marked as not
     * finalized.
     * </p>
     *
     * @param originalCode the original source code being analyzed
     */
    public AgentState(String originalCode) {
        this.originalCode = originalCode;
        this.steps = new ArrayList<>();
        this.isFinalized = false;
    }

    /**
     * Returns the original source code being analyzed.
     *
     * @return the original source code
     */
    public String getOriginalCode() { return originalCode; }

    /**
     * Sets the original source code being analyzed.
     *
     * @param originalCode the original source code to store
     */
    public void setOriginalCode(String originalCode) { this.originalCode = originalCode; }

    /**
     * Returns the final optimized source code generated by the agent.
     *
     * @return the final optimized source code, or {@code null} if no final code
     *         has been produced
     */
    public String getFinalCode() { return finalCode; }

    /**
     * Sets the final optimized source code generated by the agent.
     *
     * @param finalCode the final optimized source code to store
     */
    public void setFinalCode(String finalCode) { this.finalCode = finalCode; }

    /**
     * Returns the list of optimization steps executed by the agent.
     *
     * @return the list of agent steps
     */
    public List<AgentStep> getSteps() { return steps; }

    /**
     * Adds a new optimization step to the agent state.
     *
     * @param step the optimization step to add
     */
    public void addStep(AgentStep step) { this.steps.add(step); }

    /**
     * Indicates whether the optimization process has been finalized.
     *
     * @return {@code true} if the optimization process has been finalized;
     *         {@code false} otherwise
     */
    public boolean isFinalized() { return isFinalized; }

    /**
     * Sets whether the optimization process has been finalized.
     *
     * @param finalized {@code true} if the optimization process is finalized;
     *                  {@code false} otherwise
     */
    public void setFinalized(boolean finalized) { isFinalized = finalized; }

    /**
     * Returns the validation errors from the latest failed optimization attempt.
     *
     * @return the latest validation errors, or {@code null} if no errors have
     *         been recorded
     */
    public String getLastErrors() { return lastErrors; }

    /**
     * Sets the validation errors from the latest failed optimization attempt.
     *
     * @param lastErrors the latest validation errors to store
     */
    public void setLastErrors(String lastErrors) { this.lastErrors = lastErrors; }
}
