package ro.tuiasi.ac.agent;

import java.io.IOException;

import java.nio.file.Path;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import org.springframework.beans.factory.annotation.Value;

import ro.tuiasi.ac.service.*;
import ro.tuiasi.ac.model.*;

/**
 * Service responsible for running the optimization analysis loop for a given
 * source code file.
 *
 * <p>
 * The service reads the original code from a file, builds prompts for the AI
 * model, sends those prompts to the Gemini client, validates the generated
 * optimization proposals, and stores each iteration in an {@link AgentState}.
 * </p>
 *
 * <p>
 * The loop continues until a valid optimization proposal is produced or until
 * the configured maximum number of iterations is reached.
 * </p>
 */
@Service
public class AgentLoopService {
	/**
	 * Client service used to send prompts to the Gemini model and receive
	 * generated optimization proposals.
	 */
    @Autowired
	private GeminiClientService geminiClient;

	/**
	 * Service used to build the initial and revision prompts for the optimization
	 * process.
	 */
    @Autowired
	private PromptBuilderService promptBuilder;

	/**
	 * Service used to validate generated optimization proposals against the
	 * original source code.
	 */
    @Autowired
	private CodeValidationService validator;

	/**
	 * Service used to read source code from the provided file path.
	 */
    @Autowired
	private CodeReaderService codeReader;

	/**
	 * Maximum number of optimization iterations allowed for a single file.
	 */
	@Value("${agent.max-iterations}")
	private int maxIterations;

	/**
	 * Maximum file size configured for the scanner.
	 *
	 * <p>
	 * Currently, this field is injected from configuration but is not used inside
	 * this class.
	 * </p>
	 */
	@Value("${scanner.max-file-size}")
	private int size;

	/**
	 * Analyzes the source code file located at the given path and attempts to
	 * generate an optimized version of its contents.
	 *
	 * <p>
	 * The method performs the following steps:
	 * </p>
	 *
	 * <ol>
	 *   <li>Reads the original source code from the provided file path.</li>
	 *   <li>Initializes an {@link AgentState} with the original code.</li>
	 *   <li>Generates an initial optimization proposal using the Gemini client.</li>
	 *   <li>Validates the generated proposal.</li>
	 *   <li>If validation fails, sends the validation errors back into the next
	 *       prompt and requests a revised proposal.</li>
	 *   <li>Repeats the process until a valid proposal is found or the maximum
	 *       number of iterations is reached.</li>
	 *   <li>Returns an {@link OptimizationSuggestion} containing the original code
	 *       and the latest generated proposal.</li>
	 * </ol>
	 *
	 * @param filePath the path of the source code file to analyze
	 * @return an {@link OptimizationSuggestion} containing the original code and
	 *         the cleaned optimization proposal generated by the agent
	 * @throws IOException if the source code file cannot be read
	 */
	public OptimizationSuggestion analyze(Path filePath) throws IOException {
		String originalCode = codeReader.fileRead(filePath);
		AgentState state = new AgentState(originalCode);
		String currentProposal = "";
		for (int i = 1; i <= maxIterations; i++) {
			String prompt = (i == 1) ? promptBuilder.FirstOptimizationPrompt(filePath, originalCode)
					: promptBuilder.LoopOptimizationPrompt(filePath, originalCode, currentProposal,
							state.getLastErrors());

			currentProposal = geminiClient.generate(prompt);

			ValidationResult vResult = validator.validate(originalCode, currentProposal, filePath);
			String errorMessages = String.join(";", vResult.getErrors());
			AgentStep step = new AgentStep(i, (i == 1) ? "INITIAL_PROPOSAL" : "REVISION", currentProposal,
					vResult.isValid() ? "SUCCESS" : "FAILED", errorMessages);

			state.addStep(step);
			if (vResult.isValid()) {
				state.setFinalized(true);
				state.setFinalCode(currentProposal);
				break;
			} else {

				state.setLastErrors(errorMessages);
			}
		}
		
		OptimizationSuggestion sugestion = new OptimizationSuggestion(filePath, originalCode, validator.cleanMarkdown(currentProposal), false);
		
		return sugestion;
	}
}
