package ro.tuiasi.ac.model;

import java.util.List;

/**
 * Represents the result of an optimization analysis.
 *
 * <p>The report contains the list of optimization suggestions along with
 * summary statistics and any errors encountered during processing.</p>
 *
 * @param suggestions   the optimization suggestions generated by the analysis
 * @param totalAnalyzed the total number of items or changes analyzed
 * @param totalAccepted the total number of suggestions accepted
 * @param totalRejected the total number of suggestions rejected
 * @param errors        the list of errors encountered during the analysis
 */
public record OptimizationReport(
		List<OptimizationSuggestion> suggestions, int totalAnalyzed,
		int totalAccepted,int totalRejected, List<String> errors) {}
