package ro.tuiasi.ac.service;

import com.google.genai.Client;
import io.github.cdimascio.dotenv.Dotenv;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;

import jakarta.annotation.PostConstruct;

/**
 * Service class responsible for handling interactions with the Google Gemini API.
 * <p>
 * This service provides a mechanism to send prompts to the Gemini model and retrieve the generated responses.
 * It also supports a mock mode, which bypasses actual API calls and returns predefined responses. 
 * This is particularly useful for testing or local development environments where API access is restricted 
 * or to prevent unnecessary quota usage.
 * </p>
 */
@Service
public class GeminiClientService {
	/**
	 * Dotenv instance used to load environment variables from a local .env file.
	 */
	Dotenv dotenv = Dotenv.load();

	/**
	 * The API key for authenticating with the Gemini API, loaded from the environment variables.
	 */
	String apiKey = dotenv.get("GEMINI_API_KEY");

	/**
	 * Flag indicating whether the service should operate in mock mode.
	 * If true, API calls are bypassed and mock responses are returned.
	 * Injected via Spring application properties.
	 */
	@Value("${app.mock-mode}")
	private boolean isMockMode;

	/**
	 * The specific Gemini model identifier to be used for content generation (e.g., gemini-1.5-flash).
	 * Injected via Spring application properties.
	 */
	@Value("${gemini.model}")
	private String model;

	/**
	 * The Google GenAI client instance used to communicate with the API.
	 */
	private Client client;

	/**
	 * Initializes the Gemini service.
	 * <p>
	 * This method is executed automatically by the Spring container after dependency injection is complete.
	 * It constructs the GenAI {@link Client} using the configured API key, provided the application
	 * is not currently running in mock mode.
	 * </p>
	 */
	@PostConstruct
	public void init() {
		if (!isMockMode) {
			this.client = Client.builder()
					.apiKey(apiKey)
					.build();
		}
	}

	/**
	 * Generates content based on the provided text prompt.
	 * <p>
	 * If the service is configured to run in mock mode, a predefined mock response is returned immediately.
	 * Otherwise, an actual call to the configured Gemini API model is performed.
	 * </p>
	 *
	 * @param prompt The input text prompt or instructions to send to the model.
	 * @return The text content generated by the model, or a static string if running in mock mode.
	 */
	public String generate(String prompt) {
		if (isMockMode) {
			return generateMockResponse();
		}

		return callGeminiApi(prompt);
	}

	/**
	 * Executes the actual synchronous API call to the Google Gemini service.
	 *
	 * @param prompt The input text prompt to send to the API.
	 * @return The plain text response extracted from the model's generated content.
	 */
	private String callGeminiApi(String prompt) {
		var response = client.models.generateContent(model, prompt, null);
		return response.text();
	}

	/**
	 * Provides a static, predefined mock response for testing purposes.
	 *
	 * @return A string containing a simulated API response, formatted as a markdown Java code block.
	 */
	private String generateMockResponse() {
		return "```java\n" +
				"public class OptimizedCode {\n" +
				"    public static void main(String[] args) {\n" +
				"        System.out.println(\"Hello Optimized World\");\n" +
				"    }\n" +
				"}\n" +
				"```";
	}
}